# Generated by Django 5.2.9 on 2025-12-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SsqDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='期号')),
                ('draw_date', models.DateField(db_index=True, verbose_name='开奖日期')),
                ('red_balls', models.JSONField(default=list, verbose_name='红球')),
                ('blue_ball', models.IntegerField(default=0, verbose_name='蓝球')),
                ('red_sum', models.IntegerField(default=0, verbose_name='红球和值')),
                ('red_odd_count', models.IntegerField(default=0, verbose_name='红球奇数个数')),
                ('red_even_count', models.IntegerField(default=0, verbose_name='红球偶数个数')),
                ('red_prime_count', models.IntegerField(default=0, verbose_name='红球质数个数')),
                ('red_zones', models.JSONField(default=list, verbose_name='红球三区分布')),
                ('red_span', models.IntegerField(default=0, verbose_name='红球跨度')),
                ('red_ac_value', models.IntegerField(default=0, verbose_name='红球AC值')),
                ('red_tail_sum', models.IntegerField(default=0, verbose_name='红球尾数和')),
                ('hot_numbers', models.JSONField(default=list, verbose_name='热号')),
                ('cold_numbers', models.JSONField(default=list, verbose_name='冷号')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('prediction_difficulty', models.FloatField(default=0.5, help_text='基于历史模式计算的预测难度，0-1之间', verbose_name='预测难度系数')),
                ('feature_group', models.CharField(choices=[('normal', '常规模式'), ('anomaly', '异常模式'), ('pattern', '规律模式'), ('random', '随机模式')], default='normal', max_length=20, verbose_name='特征组别')),
            ],
            options={
                'ordering': ['-period'],
                'indexes': [models.Index(fields=['period'], name='ssq_ssqdraw_period_6739f3_idx'), models.Index(fields=['draw_date'], name='ssq_ssqdraw_draw_da_e16174_idx')],
                'constraints': [models.UniqueConstraint(fields=('period', 'draw_date'), name='unique_period_date')],
            },
        ),
    ]
