# Generated by Django 5.2.9 on 2026-01-02 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ssqdraw',
            options={'ordering': ['-period'], 'verbose_name': '双色球开奖记录', 'verbose_name_plural': '双色球开奖记录'},
        ),
    ]
