# Generated by Django 5.2.9 on 2026-01-02 20:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SsqFeatureSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, validators=[django.core.validators.MinLengthValidator(1, '特征集名称不能为空')], verbose_name='特征集名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('feature_columns', models.JSONField(default=list, verbose_name='特征列')),
                ('target_columns', models.JSONField(default=list, verbose_name='目标列')),
                ('period_start', models.CharField(db_index=True, max_length=20, verbose_name='开始期号')),
                ('period_end', models.CharField(db_index=True, max_length=20, verbose_name='结束期号')),
                ('sample_count', models.IntegerField(default=0, verbose_name='样本数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '特征数据集',
                'verbose_name_plural': '特征数据集',
                'db_table': 'ssq_features',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['period_start', 'period_end'], name='idx_period_start_end')],
                'constraints': [models.UniqueConstraint(fields=('name', 'period_start', 'period_end'), name='unique_feature_name_period', violation_error_message='相同名称+时间范围的特征集已存在')],
            },
        ),
        migrations.CreateModel(
            name='SsqModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='模型名称')),
                ('model_type', models.CharField(choices=[('RF', 'Random Forest'), ('LGB', 'LightGBM'), ('XGB', 'XGBoost'), ('NN', 'Neural Network'), ('Transformer', 'Transformer'), ('Ensemble', 'Ensemble')], max_length=20, verbose_name='模型类型')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='版本号')),
                ('ensemble_weights', models.JSONField(blank=True, default=list, help_text='各子模型的权重列表，如[0.4, 0.3, 0.3]', verbose_name='集成权重')),
                ('transformer_config', models.JSONField(blank=True, default=dict, help_text='Transformer模型超参数配置', verbose_name='Transformer配置')),
                ('train_period_start', models.CharField(db_index=True, max_length=20, verbose_name='训练开始期号')),
                ('train_period_end', models.CharField(db_index=True, max_length=20, verbose_name='训练结束期号')),
                ('train_score', models.FloatField(blank=True, null=True, verbose_name='训练分数')),
                ('val_score', models.FloatField(blank=True, null=True, verbose_name='验证分数')),
                ('test_score', models.FloatField(blank=True, null=True, verbose_name='测试分数')),
                ('metrics', models.JSONField(blank=True, default=dict, verbose_name='评估指标')),
                ('model_file', models.FileField(help_text='支持.pkl/.h5/.pt格式', upload_to='models/%Y/%m/%d/', verbose_name='模型文件')),
                ('config_file', models.FileField(blank=True, null=True, upload_to='configs/%Y/%m/%d/', verbose_name='配置文件')),
                ('model_hash', models.CharField(editable=False, max_length=64, unique=True, verbose_name='模型文件Hash')),
                ('feature_importance', models.JSONField(blank=True, default=dict, verbose_name='特征重要性')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='模型参数')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否激活')),
                ('red_ball_range', models.JSONField(default=[1, 33], help_text='红球号码范围，如[1, 33]', verbose_name='红球范围')),
                ('blue_ball_range', models.JSONField(default=[1, 16], help_text='蓝球号码范围，如[1, 16]', verbose_name='蓝球范围')),
                ('red_ball_metrics', models.JSONField(blank=True, default=dict, help_text='红球相关的评估指标', verbose_name='红球评估指标')),
                ('blue_ball_metrics', models.JSONField(blank=True, default=dict, help_text='蓝球相关的评估指标', verbose_name='蓝球评估指标')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ensemble_models', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='ensemble_components', to='ai_models.ssqmodel', verbose_name='集成组件模型')),
                ('feature_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='ai_models.ssqfeatureset', verbose_name='关联特征集')),
            ],
            options={
                'verbose_name': '预测模型',
                'verbose_name_plural': '预测模型',
                'db_table': 'ssq_models',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('name', 'version'), name='uniq_model_name_version')],
            },
        ),
    ]
